	<nav id="main">
		<ul>
			<li><a href="#">Home</a></li>
			<li><a href="#">Client Site</a> </li>
			<li><a href="#">Protosite</a> </li>
		</ul>
	</nav>

	<nav id="leftcolumn">

		<section>
			<h3>Project Overview</h3>
	        <ul>															
	            <li> <a href="#">Project Goals</a></li>
				<li> <a href="#">Wireframe</a></li>
	            <li> <a href="#">Sitemap</a></li>
	            <li> <a href="#">Rationale</a></li>
				<li> <a href="#">Artifacts</a></li>
		    </ul>
	 	</section>

	 	<section>
	 		<h3>Contact</h3>
	        <ul>															
	            <li> <a href="#">something</a></li>
		    </ul>
	 	</section>

	</nav>