<nav id="main">
	<ul>
	 <li><a href="">Client Site</a></li>
	 <li><a href="proto_01.shtml">Protosite</a></li>
	</ul>
</nav>

<nav id="leftcolumn">
	<section>
		<h3>Project Overview</h3>
		        <ul>															
			 <li> <a href="client_project_goal.shtml">Project Goal</a></li>
			 <li> <a href="client_wireframe.shtml">Wireframe</a></li>
		         <li> <a href="client_sitemap.shtml">Sitemap</a></li>
			 <li> <a href="client_rationale.shtml">Rationale</a></li>
			 <li> <a href="client_artifacts.shtml">Artifacts</a></li>
			</ul>
	</section>
 	<section>
		<h3>Contact(s)</h3>
		        <ul>															
			 <li> <a href="client_project_goal.shtml">Project Team</a></li>
		        </ul>
 	</section>
</nav>