    <nav id="main">
     
		<ul>
			<li><a href="#">Home</a> </li>
			<li><a href="#">Activities</a></li>
			<li><a href="#">Validate</a> </li>
			<li><a href="#">Contact</a></li>
		</ul>
	
    <form id="search">
        <input type="text" value="" maxlength="255" size="20" name="q">
        <input type="submit" value="Search">
    </form>
	

	</nav>	
      <aside>   
        <div id="leftcolumn">
         <h3>Lectures</h3>
         <ul>															
            <li> <a href="proto_01.shtml">01 | Introduction</a></li>           	
            <li> <a href="proto_02.shtml">02 | Tools & Standards</a></li>
            <li> <a href="#">03 | HTML5 & SEO</a></li>
			<li> <a href="#">04 | CSS Concepts</a></li>
			<li> <a href="#">05 | More CSS</a></li>
			<li> <a href="#">06 | CSS and SSIs</a></li>
			<li> <a href="#">07 | templates</a></li>
			<li> <a href="#">09 | methodology</a></li>
			<li> <a href="#">10 | jQuery / Git</a></li>
				
	     </ul>
			<div id="media-hide"> 
				<h3>Examples and Blog</h3>
				<ul>
				<li><a href="proto_example_code.shtml">Example Codes</a></li>
				<li><a href="#">Exercises</a></li>
				<li><a href="#">Assignments</a></li>			
				<li><a href="proto_blog.shtml">Blog</a></li>			
				</ul>
			 
			
			  <h3>Resources</h3>
				<ul>
				<li><a href="https://my.bcit.ca/">my.bcit</a></li>
				<li><a href="http://www.bcit.ca/">bcit</a></li>	
				<li><a href="http://www.bcit.ca/cas/computing/">bcit:computing</a></li>
				<li><a href="http://www.alistair.com/">alistair.com</a></li>			
				</ul>
			</div>
		 </div>
   </aside>	